- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  setPreference: true # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Medical
  - Chemistry
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  #storage:
    #back:
    #- Stuff
