- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  setPreference: true # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Medical
  - Chemistry
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
